package com.jll.entity;
// Generated 2018-7-25 12:24:23 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * DepositApplication generated by hbm2java
 */
public class DepositApplication implements java.io.Serializable {

	private Integer id;
	private String orderNum;
	private Integer userId;
	private Float amount;
	private Integer payType;
	private Integer payChannel;
	private String platAccount;
	private Date createTime;
	private Date updateTime;
	private String remark;
	private Integer state;

	public DepositApplication() {
	}

	public DepositApplication(String orderNum, Integer userId, Float amount, Integer payType, Integer payChannel,
			String platAccount, Date createTime, Date updateTime, String remark, Integer state) {
		this.orderNum = orderNum;
		this.userId = userId;
		this.amount = amount;
		this.payType = payType;
		this.payChannel = payChannel;
		this.platAccount = platAccount;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.remark = remark;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public Integer getPayType() {
		return this.payType;
	}

	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	public Integer getPayChannel() {
		return this.payChannel;
	}

	public void setPayChannel(Integer payChannel) {
		this.payChannel = payChannel;
	}

	public String getPlatAccount() {
		return this.platAccount;
	}

	public void setPlatAccount(String platAccount) {
		this.platAccount = platAccount;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

}
