package com.jll.entity;
// Generated 2018-8-8 15:26:50 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * Issue generated by hbm2java
 */
public class GenSequence implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -162220270110557773L;
	
	private Integer id;
	private String seqName;
	private Long seqVal;
	
	public GenSequence() {
	}

	public GenSequence(String seqName, Long seqVal) {
		this.seqName = seqName;
		this.seqVal = seqVal;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSeqName() {
		return seqName;
	}

	public void setSeqName(String seqName) {
		this.seqName = seqName;
	}

	public Long getSeqVal() {
		return seqVal;
	}

	public void setSeqVal(Long seqVal) {
		this.seqVal = seqVal;
	}

	
}
