package com.jll.entity;
// Generated 2018-8-14 16:52:58 by Hibernate Tools 5.2.10.Final


/**
 * Issue generated by hbm2java
 */
public class IpBlackList implements java.io.Serializable {
	/**
	 * 
	 */
	
	private Integer id;

	private String ip;
	
	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public IpBlackList() {
	}

	public IpBlackList(String ip) {
		this.ip = ip;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
}
