package com.jll.entity;
// Generated 2018-8-8 15:26:50 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * OrderSource generated by hbm2java
 */
public class OrderSource implements java.io.Serializable {

	private Integer id;
	private Date createTime;
	private String codeName;
	private BigDecimal mobileAmount;
	private BigDecimal pcAmount;
	private BigDecimal sumAmount;

	public OrderSource() {
	}

	public OrderSource(Date createTime) {
		this.createTime = createTime;
	}

	public OrderSource(Date createTime, String codeName, BigDecimal mobileAmount,
			BigDecimal pcAmount, BigDecimal sumAmount) {
		this.createTime = createTime;
		this.codeName = codeName;
		this.mobileAmount = mobileAmount;
		this.pcAmount = pcAmount;
		this.sumAmount = sumAmount;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	public BigDecimal getMobileAmount() {
		return this.mobileAmount;
	}

	public void setMobileAmount(BigDecimal mobileAmount) {
		this.mobileAmount = mobileAmount;
	}

	public BigDecimal getPcAmount() {
		return this.pcAmount;
	}

	public void setPcAmount(BigDecimal pcAmount) {
		this.pcAmount = pcAmount;
	}

	public BigDecimal getSumAmount() {
		return this.sumAmount;
	}

	public void setSumAmount(BigDecimal sumAmount) {
		this.sumAmount = sumAmount;
	}

}
