package com.jll.entity;
// Generated 2018-8-14 16:52:58 by Hibernate Tools 5.2.10.Final

/**
 * PayChannel generated by hbm2java
 */
public class PayChannel implements java.io.Serializable {

	private Integer id;
	private String channelName;
	private String nickName;
	private String typeClass;
	private String type;
	private Float maxAmount;
	private Integer enableMaxAmount;
	private Integer seq;
	private Integer state;
	private String qrUrl;
	private String bankAcc;
	private String bankName;
	private String remark;

	public PayChannel() {
	}

	public PayChannel(String channelName, String nickName, String typeClass, String type, Float maxAmount,
			Integer enableMaxAmount, Integer seq, Integer state, String qrUrl, String bankAcc, String bankName,
			String remark) {
		this.channelName = channelName;
		this.nickName = nickName;
		this.typeClass = typeClass;
		this.type = type;
		this.maxAmount = maxAmount;
		this.enableMaxAmount = enableMaxAmount;
		this.seq = seq;
		this.state = state;
		this.qrUrl = qrUrl;
		this.bankAcc = bankAcc;
		this.bankName = bankName;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getChannelName() {
		return this.channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getTypeClass() {
		return this.typeClass;
	}

	public void setTypeClass(String typeClass) {
		this.typeClass = typeClass;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Float getMaxAmount() {
		return this.maxAmount;
	}

	public void setMaxAmount(Float maxAmount) {
		this.maxAmount = maxAmount;
	}

	public Integer getEnableMaxAmount() {
		return this.enableMaxAmount;
	}

	public void setEnableMaxAmount(Integer enableMaxAmount) {
		this.enableMaxAmount = enableMaxAmount;
	}

	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getQrUrl() {
		return this.qrUrl;
	}

	public void setQrUrl(String qrUrl) {
		this.qrUrl = qrUrl;
	}

	public String getBankAcc() {
		return this.bankAcc;
	}

	public void setBankAcc(String bankAcc) {
		this.bankAcc = bankAcc;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
