package com.jll.entity;
// Generated 2018-8-14 16:52:58 by Hibernate Tools 5.2.10.Final

/**
 * PayChannel generated by hbm2java
 */
public class PayChannel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2678478216909424604L;
	private Integer id;
	private String channelName;
	private String nickName;
	private String typeClass;
	private Integer payType;
	private Float maxAmount;
	private Integer enableMaxAmount;
	private Integer seq;
	private Integer state;
	private String qrUrl;
	private String bankAcc;
	private String bankName;
	private String remark;
	private String payCode;
	private Integer showType;

	public PayChannel() {
	}

	public PayChannel(String channelName, String nickName, String typeClass, Integer payType, Float maxAmount,
			Integer enableMaxAmount, Integer seq, Integer state, String qrUrl, String bankAcc, String bankName,
			String remark, String payCode, Integer showType) {
		super();
		this.channelName = channelName;
		this.nickName = nickName;
		this.typeClass = typeClass;
		this.payType = payType;
		this.maxAmount = maxAmount;
		this.enableMaxAmount = enableMaxAmount;
		this.seq = seq;
		this.state = state;
		this.qrUrl = qrUrl;
		this.bankAcc = bankAcc;
		this.bankName = bankName;
		this.remark = remark;
		this.payCode = payCode;
		this.showType = showType;
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getChannelName() {
		return this.channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getTypeClass() {
		return this.typeClass;
	}

	public void setTypeClass(String typeClass) {
		this.typeClass = typeClass;
	}
	
	public Integer getPayType() {
		return payType;
	}

	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	public Float getMaxAmount() {
		return this.maxAmount;
	}

	public void setMaxAmount(Float maxAmount) {
		this.maxAmount = maxAmount;
	}

	public Integer getEnableMaxAmount() {
		return this.enableMaxAmount;
	}

	public void setEnableMaxAmount(Integer enableMaxAmount) {
		this.enableMaxAmount = enableMaxAmount;
	}

	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getQrUrl() {
		return this.qrUrl;
	}

	public void setQrUrl(String qrUrl) {
		this.qrUrl = qrUrl;
	}

	public String getBankAcc() {
		return this.bankAcc;
	}

	public void setBankAcc(String bankAcc) {
		this.bankAcc = bankAcc;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getPayCode() {
		return payCode;
	}

	public void setPayCode(String payCode) {
		this.payCode = payCode;
	}

	public Integer getShowType() {
		return showType;
	}

	public void setShowType(Integer showType) {
		this.showType = showType;
	}

}
