package com.jll.entity;
// Generated 2018-8-8 15:26:50 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * PlatformFundSummary generated by hbm2java
 */
public class PlatformFundSummary implements java.io.Serializable {

	private Integer id;
	private Date createTime;
	private BigDecimal freezingFunds;
	private BigDecimal allBalances;
	private BigDecimal recharge;
	private BigDecimal withdraw;

	public PlatformFundSummary() {
	}

	public PlatformFundSummary(Date createTime, BigDecimal freezingFunds, BigDecimal allBalances, BigDecimal recharge,
			BigDecimal withdraw) {
		this.createTime = createTime;
		this.freezingFunds = freezingFunds;
		this.allBalances = allBalances;
		this.recharge = recharge;
		this.withdraw = withdraw;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public BigDecimal getFreezingFunds() {
		return this.freezingFunds;
	}

	public void setFreezingFunds(BigDecimal freezingFunds) {
		this.freezingFunds = freezingFunds;
	}

	public BigDecimal getAllBalances() {
		return this.allBalances;
	}

	public void setAllBalances(BigDecimal allBalances) {
		this.allBalances = allBalances;
	}

	public BigDecimal getRecharge() {
		return this.recharge;
	}

	public void setRecharge(BigDecimal recharge) {
		this.recharge = recharge;
	}

	public BigDecimal getWithdraw() {
		return this.withdraw;
	}

	public void setWithdraw(BigDecimal withdraw) {
		this.withdraw = withdraw;
	}

}
