package com.jll.entity;
// Generated 2018-8-8 15:26:50 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * PlayType generated by hbm2java
 */
public class PlayType implements java.io.Serializable {

	private Integer id;
	private String lotteryType;
	private String classification;
	private String ptName;
	private String ptDesc;
	private Integer state;
	private Integer mulSinFlag;
	private Integer isHidden;
	private Integer seq;
	private Date createTime;

	public PlayType() {
	}

	public PlayType(String lotteryType, String classification,String ptName, String ptDesc, Integer state, Integer mulSinFlag ,Integer isHidden,Integer seq, Date createTime) {
		this.lotteryType = lotteryType;
		this.classification=classification;
		this.ptName = ptName;
		this.ptDesc = ptDesc;
		this.state = state;
		this.mulSinFlag = mulSinFlag;
		this.isHidden = isHidden;
		this.seq = seq;
		this.createTime = createTime;
	}
	
	public Integer getIsHidden() {
		return isHidden;
	}

	public void setIsHidden(Integer isHidden) {
		this.isHidden = isHidden;
	}

	public Integer getMulSinFlag() {
		return mulSinFlag;
	}

	public void setMulSinFlag(Integer mulSinFlag) {
		this.mulSinFlag = mulSinFlag;
	}

	public String getClassification() {
		return classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLotteryType() {
		return this.lotteryType;
	}

	public void setLotteryType(String lotteryType) {
		this.lotteryType = lotteryType;
	}
	
	public String getPtName() {
		return ptName;
	}

	public void setPtName(String ptName) {
		this.ptName = ptName;
	}

	public String getPtDesc() {
		return ptDesc;
	}

	public void setPtDesc(String ptDesc) {
		this.ptDesc = ptDesc;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
