package com.jll.entity;
// Generated 2018-7-18 10:09:13 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * PromoClaim generated by hbm2java
 */
public class PromoClaim implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private Integer promoId;
	private Date claimTime;

	public PromoClaim() {
	}

	public PromoClaim(Integer userId, Integer promoId, Date claimTime) {
		this.userId = userId;
		this.promoId = promoId;
		this.claimTime = claimTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getPromoId() {
		return this.promoId;
	}

	public void setPromoId(Integer promoId) {
		this.promoId = promoId;
	}

	public Date getClaimTime() {
		return this.claimTime;
	}

	public void setClaimTime(Date claimTime) {
		this.claimTime = claimTime;
	}

}
