package com.jll.entity;
// Generated 2018-8-8 15:26:50 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * SignupRec generated by hbm2java
 */
public class SignupRec implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private Integer rewardPoints;
	private Date createTime;

	public SignupRec() {
	}

	public SignupRec(Integer userId, Integer rewardPoints, Date createTime) {
		this.userId = userId;
		this.rewardPoints = rewardPoints;
		this.createTime = createTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getRewardPoints() {
		return this.rewardPoints;
	}

	public void setRewardPoints(Integer rewardPoints) {
		this.rewardPoints = rewardPoints;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
