package com.jll.entity;
// Generated 2018-8-14 16:52:58 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * SiteMessage generated by hbm2java
 */
public class SiteMessage implements java.io.Serializable {

	private Integer id;
	private String title;
	private String content;
	private Date expireTime;
	private Integer receiver;
	private Integer isRead;
	private Date createTime;
	private Integer creator;
	private Integer userId;

	public SiteMessage() {
	}

	public SiteMessage(String title, String content, Date expireTime, Integer receiver, Integer isRead, Date createTime,
			Integer creator, Integer userId) {
		this.title = title;
		this.content = content;
		this.expireTime = expireTime;
		this.receiver = receiver;
		this.isRead = isRead;
		this.createTime = createTime;
		this.creator = creator;
		this.userId = userId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getExpireTime() {
		return this.expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	public Integer getReceiver() {
		return this.receiver;
	}

	public void setReceiver(Integer receiver) {
		this.receiver = receiver;
	}

	public Integer getIsRead() {
		return this.isRead;
	}

	public void setIsRead(Integer isRead) {
		this.isRead = isRead;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getCreator() {
		return this.creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
