package com.jll.entity;
// Generated 2018-7-25 12:24:23 by Hibernate Tools 5.2.10.Final

/**
 * SysAuthority generated by hbm2java
 */
public class SysAuthority implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private Integer roleId;

	public SysAuthority() {
	}

	public SysAuthority(Integer userId, Integer roleId) {
		this.userId = userId;
		this.roleId = roleId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

}
