package com.jll.entity;
// Generated 2018-8-14 16:52:58 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * SysCode generated by hbm2java
 */
public class SysLog implements java.io.Serializable {

	private Integer id;
	private String logType;
	private String logOpeType;
	private Integer userId;
	private String logData;
	private Date createTime;

	public SysLog() {
	}

	public SysLog(String logType, String logOpeType, Integer userId, String logData, Date createTime) {
		this.logType = logType;
		this.logOpeType = logOpeType;
		this.userId = userId;
		this.logData = logData;
		this.createTime = createTime;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLogType() {
		return logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	public String getLogOpeType() {
		return logOpeType;
	}

	public void setLogOpeType(String logOpeType) {
		this.logOpeType = logOpeType;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getLogData() {
		return logData;
	}

	public void setLogData(String logData) {
		this.logData = logData;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
}
