package com.jll.entity;
// Generated 2018-7-26 11:57:20 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * SysRole generated by hbm2java
 */
public class SysRole implements java.io.Serializable {

	private Integer id;
	private String roleName;
	private String roleDesc;
	private Integer state;
	private Integer creator;
	private Date createTime;

	public SysRole() {
	}

	public SysRole(String roleName, String roleDesc, Integer state, Integer creator, Date createTime) {
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.state = state;
		this.creator = creator;
		this.createTime = createTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Integer getCreator() {
		return this.creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
