package com.jll.entity;
// Generated 2018-7-18 10:09:13 by Hibernate Tools 5.2.10.Final

/**
 * TpNotices generated by hbm2java
 */
public class TpNotices implements java.io.Serializable {

	private TpNoticesId id;

	public TpNotices() {
	}

	public TpNotices(TpNoticesId id) {
		this.id = id;
	}

	public TpNoticesId getId() {
		return this.id;
	}

	public void setId(TpNoticesId id) {
		this.id = id;
	}

}
