package com.jll.entity;
// Generated 2018-7-18 10:09:13 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * TpNoticesId generated by hbm2java
 */
public class TpNoticesId implements java.io.Serializable {

	private String result;
	private Float amount;
	private String orderNum;
	private String transactionNum;
	private Date createTime;

	public TpNoticesId() {
	}

	public TpNoticesId(String result, Float amount, String orderNum, String transactionNum, Date createTime) {
		this.result = result;
		this.amount = amount;
		this.orderNum = orderNum;
		this.transactionNum = transactionNum;
		this.createTime = createTime;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public String getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	public String getTransactionNum() {
		return this.transactionNum;
	}

	public void setTransactionNum(String transactionNum) {
		this.transactionNum = transactionNum;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TpNoticesId))
			return false;
		TpNoticesId castOther = (TpNoticesId) other;

		return ((this.getResult() == castOther.getResult()) || (this.getResult() != null
				&& castOther.getResult() != null && this.getResult().equals(castOther.getResult())))
				&& ((this.getAmount() == castOther.getAmount()) || (this.getAmount() != null
						&& castOther.getAmount() != null && this.getAmount().equals(castOther.getAmount())))
				&& ((this.getOrderNum() == castOther.getOrderNum()) || (this.getOrderNum() != null
						&& castOther.getOrderNum() != null && this.getOrderNum().equals(castOther.getOrderNum())))
				&& ((this.getTransactionNum() == castOther.getTransactionNum())
						|| (this.getTransactionNum() != null && castOther.getTransactionNum() != null
								&& this.getTransactionNum().equals(castOther.getTransactionNum())))
				&& ((this.getCreateTime() == castOther.getCreateTime())
						|| (this.getCreateTime() != null && castOther.getCreateTime() != null
								&& this.getCreateTime().equals(castOther.getCreateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getResult() == null ? 0 : this.getResult().hashCode());
		result = 37 * result + (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result + (getOrderNum() == null ? 0 : this.getOrderNum().hashCode());
		result = 37 * result + (getTransactionNum() == null ? 0 : this.getTransactionNum().hashCode());
		result = 37 * result + (getCreateTime() == null ? 0 : this.getCreateTime().hashCode());
		return result;
	}

}
