package com.jll.entity;
// Generated 2018-8-14 16:52:58 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * UserBankCard generated by hbm2java
 */
public class UserBankCard implements java.io.Serializable {

	private Integer id;
	private String cardNum;
	private Integer userId;
	private String bankBranch;
	private String bankCode;
	private Integer state;
	private Integer creator;
	private Date createTime;
	private String remark;

	public UserBankCard() {
	}

	public UserBankCard(String cardNum, Integer userId, String bankBranch, String bankCode, Integer state,
			Integer creator, Date createTime, String remark) {
		this.cardNum = cardNum;
		this.userId = userId;
		this.bankBranch = bankBranch;
		this.bankCode = bankCode;
		this.state = state;
		this.creator = creator;
		this.createTime = createTime;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCardNum() {
		return this.cardNum;
	}

	public void setCardNum(String cardNum) {
		this.cardNum = cardNum;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getBankBranch() {
		return this.bankBranch;
	}

	public void setBankBranch(String bankBranch) {
		this.bankBranch = bankBranch;
	}

	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Integer getCreator() {
		return this.creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
