package com.jll.entity;
// Generated 2018-7-18 10:09:13 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * UserAccountDetails generated by hbm2java
 */
public class UserAccountDetails implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private Float amount;
	private Float preAmount;
	private Float postAmount;
	private Integer walletId;
	private Integer orderId;
	private String operationType;
	private Date createTime;

	public UserAccountDetails() {
	}

	public UserAccountDetails(Integer userId, Float amount, Float preAmount, Float postAmount, Integer walletId,
			Integer orderId, String operationType, Date createTime) {
		this.userId = userId;
		this.amount = amount;
		this.preAmount = preAmount;
		this.postAmount = postAmount;
		this.walletId = walletId;
		this.orderId = orderId;
		this.operationType = operationType;
		this.createTime = createTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public Float getPreAmount() {
		return this.preAmount;
	}

	public void setPreAmount(Float preAmount) {
		this.preAmount = preAmount;
	}

	public Float getPostAmount() {
		return this.postAmount;
	}

	public void setPostAmount(Float postAmount) {
		this.postAmount = postAmount;
	}

	public Integer getWalletId() {
		return this.walletId;
	}

	public void setWalletId(Integer walletId) {
		this.walletId = walletId;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public String getOperationType() {
		return this.operationType;
	}

	public void setOperationType(String operationType) {
		this.operationType = operationType;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
