package com.jll.entity;
// Generated 2018-7-18 10:09:13 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * WithdrawApplication generated by hbm2java
 */
public class WithdrawApplication implements java.io.Serializable {

	private Integer id;
	private String orderNum;
	private Integer userId;
	private Float amount;
	private Integer walletId;
	private Integer bankCardId;
	private Integer state;
	private Date createTime;
	private Date updateTime;
	private Integer operator;
	private String remark;

	public WithdrawApplication() {
	}

	public WithdrawApplication(String orderNum, Integer userId, Float amount, Integer walletId, Integer bankCardId,
			Integer state, Date createTime, Date updateTime, Integer operator, String remark) {
		this.orderNum = orderNum;
		this.userId = userId;
		this.amount = amount;
		this.walletId = walletId;
		this.bankCardId = bankCardId;
		this.state = state;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.operator = operator;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public Integer getWalletId() {
		return this.walletId;
	}

	public void setWalletId(Integer walletId) {
		this.walletId = walletId;
	}

	public Integer getBankCardId() {
		return this.bankCardId;
	}

	public void setBankCardId(Integer bankCardId) {
		this.bankCardId = bankCardId;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getOperator() {
		return this.operator;
	}

	public void setOperator(Integer operator) {
		this.operator = operator;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
